### ISSUE TITLE
[Bug]:  create window when app getting active

### ISSUE THREAD

**Issue by modudibai** [iamWing/electron-react-typescript-base-proj#47]
### Version

lastest

### Steps to reproduce

none

### Expected behaviour

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });

### Actual behaviour

app.on('activate', () => {
    if (BrowserWindow.getAllWindows.length === 0) createWindow();
  });

### Additional context

code mistake

### Environment

```Shell
all
```

**Comment by modudibai** [comment]
will always trigger createWindow() when app become active, It doesn't make sense

**Comment by iamWing** [comment]
Hi @modudibai, thanks for submitting the issue, will include the code fixe in the next release. Btw I'm wondering why do you think it doesn't make sense to have that `if` statement in `app.on('activate', () => (...));`? It's how you get a new window when the app icon is clicked while it's running and have no available window if my understanding is correct (I'm speaking from a Mac user POV here, not too familiar with Windows).
